### ISSUE TITLE
Ability to specify an existing VPC

### ISSUE THREAD

**Issue by marks** [ttlequals0/autovpn#10]
How hard would it be to add the ability to deploy this into an existing VPC?

**Comment by ttlequals0** [comment]
I was planning on adding a similar feature at some point. I just need to think of the best way dong this.

**Comment by dprime** [comment]
It would have to be quite configurable, so you'd need to specify at least all of the following :

- VPC
- Subnet in that VPC
- Security group(s)

And the security group would already have to work with the appropriate ports open.

An alternative would be to allow the user to specify only certain aspects of this. Eg, the user supplies a VPC, but the script then creates a subnet and a security group, or the user supplies both vpc and subnet so the script creates an appropriate SG.
