### ISSUE TITLE
[feature request] specify openvpn port

### ISSUE THREAD

**Issue by fishy** [ttlequals0/autovpn#16]
Since the EC2 instance is solely for openvpn (at least for some of the users), it would make sense to use a port with QoS, for example 443.

It would be great to make 443 the default port, or add the option to specify the port wanted.

**Comment by elijahchancey** [comment]
Setting TCP 443 would be great. I'm behind a hotel router in Indonesia that appears to be dropping UDP 1194 packets. :(

**Comment by Incedis** [comment]
I second that. I travel a lot and right now in a hotel that drops packets 1194. :(

**Comment by ttlequals0** [comment]
I have added the ability to specify a custom port with -p flag 
see: https://github.com/ttlequals0/autovpn/commit/5e16aa5a60e492b9a064e1a5c4a7ccc7c9f5a724

**Comment by imagesafari** [comment]
Is there a way to set it to use a TCP port instead of UDP?

**Comment by ttlequals0** [comment]
At this time its only UDP. As a note OpenVPN over TCP adds significant overhead.
