### ISSUE TITLE
Termination of instance 

### ISSUE THREAD

**Issue by Incedis** [ttlequals0/autovpn#24]
First off, thank you for this and very sweat program. 
I have created as a test one instance in eu-central. I terminated the instance in AWS. Tried to create a fresh key in same region but autovpn tells me the key already exist. 
I have deleted the key for instance eu-central-1 which I had forgotten. 
I got confused as far as the result of # ./autovpn -S -r eu-central-1.  It says the instance is running which is the case but thought it still believed the OpenVPN was still running on the instance.  In fact, I am getting the message "Instances running in eu-central-1" because there is indeed another instance not related to autovpn running. 
Is there a possibility to clarify the statement that we know the message is not referring to autovpn instance ?

**Comment by ttlequals0** [comment]
1. When you delete a key from AWS you also have to manually delete the pem file from you current working directory. 
2.when you check the status of instances running in a given region it only looks for instance taged with "auto_vpn". If an instance is found it will return its ID and ip.  If nothing is found it will return a blank line.

**Comment by Incedis** [comment]
Thanks for your reply. To be more clear, I had created for test in region eu-central-1 one vpn instance. I terminated the instance and deleted the key. 
Running this command "./autovpn -S -r eu-central-1" I am getting the below as a result telling me the instance autovpn is still running . I equated the "still running" message to the fact that I do have another instance running in that region. Obviously from your last response I was wrong. 
Any idea ?

File "./scripts/get_status.py", line 23
print "%s \tIP:%s" %(instance, instanceip)            
TabError: inconsistent use of tabs and spaces in indentation
Instances running in eu-central-1

**Comment by ttlequals0** [comment]
From this output there are no instances running in that region. However I do find the python traceback problematic. Were and modifications made to the script?

**Comment by Incedis** [comment]
No modification were made to the script. But then why is it saying "instances running in eu-central-1" ? your prior statement saying that it looks for a tagged instance "auto_vpn", I would expect a return of no instance running ?

**Comment by ttlequals0** [comment]
That is just the header for output. 

Example:
If instances are found:

instances running in eu-central-1
Instance-I'd instance-ip

If nothing is running:

instances running in eu-central-1
\<blank line\>

**Comment by Incedis** [comment]
Ah ok. Thanks :) Why the trace back in the code ?

**Comment by ttlequals0** [comment]
That one I'm not sure I will have to investigate. Also I will make it more clear in output when no instances are found.

**Comment by ttlequals0** [comment]
issue with traceback has been resolved see #25

**Comment by ttlequals0** [comment]
I have made changes to Status output to make it more clear 
see: https://github.com/ttlequals0/autovpn/commit/929c4c198946f7f2177aa716b38d766d81983401
