### ISSUE TITLE
Error code 4

### ISSUE THREAD

**Issue by ghost** [ttlequals0/autovpn#25]
Hey there. I've got to step 3 of the installation instructions and I'm receiving the following error. 

> ./autovpn -C -r us-west-2 -k us-west-2-vpnkey
> Creating ec2 instance in us-west-2. This can take some time...
>   File "./scripts/create_ec2.py", line 31
>     except ec2.ResponseError, e:
>                             ^
> SyntaxError: invalid syntax
> Error code 4
> 

I also tried generating a new keypair and I get the following :

> ./autovpn -G -r us-west-1
> Generating new keypair for us-west-1.
>   File "./scripts/keygen.py", line 22
>     except ec2.ResponseError, e:
>                             ^
> SyntaxError: invalid syntax
> Key already exists in AWS
> 

I'm wondering if I'm doing something wrong or if I've missed something. Any help would be appreciated. Thanks.

**Comment by ttlequals0** [comment]
Which OS are you trying to run this on. What version of python are you using?

**Comment by ghost** [comment]
Thanks for the quick reply. I'm running Arch. Python version is 3.6.0.

**Comment by ttlequals0** [comment]
Hmm. Looks to be some syntax issues with python 3. I wrote the script poorly in a python 2.7 environment.

**Comment by ghost** [comment]
Unfortunately I'm not well versed in Python otherwise I'd offer to help you out. At least you have another todo item to add to your list! Still appreciate the effort though. I do have Ubuntu that's got 2.7 running so I can use it on there.

**Comment by Amadiro** [comment]
Replacing every instance of "python" with "python2" in autovpn.sh should do the trick, AFAIR that's what I did to make it run on arch.

**Comment by ghost** [comment]
Hey Amadiro. I tried what you suggested and found out that I needed the python2 version of the specified dependencies. For posterity I then ended up [here](http://stackoverflow.com/questions/11268501/how-to-use-pip-with-python-3-x-alongside-python-2-x) and [here](http://stackoverflow.com/questions/5396932/why-are-no-amazon-s3-authentication-handlers-ready) to resolve my issue. There's probably a far easier way but this worked for me. Thanks for the help.

**Comment by Amadiro** [comment]
This should probably still be resolved in autovpn, since (I think) changing `python` to `python2` should not break anywhere, but would make things work on some systems

**Comment by ttlequals0** [comment]
fixed in https://github.com/ttlequals0/autovpn/commit/acd44360049eec408d567ea75860f15d7e89a93f
