### ISSUE TITLE
Similar project for Azure

### ISSUE THREAD

**Issue by jhagege** [ttlequals0/autovpn#26]
Hi, 

Thanks again for this excellent script. I'm using it with AWS and it works perfectly.
Do you know of a similar existing project for deployment on Microsoft Azure.

Do you think it would take a lot of work to adapt it to work with Azure ? 

Thanks !

**Comment by ttlequals0** [comment]
Thank you, 

 am not sure if there is any similar projects for Azure. However if someone were to this project would be a good starting point.
