### ISSUE TITLE
error code 5

### ISSUE THREAD

**Issue by Incedis** [ttlequals0/autovpn#28]
can't proceed further. I am getting error code 5 with no details 

Any idea ?

**Comment by ttlequals0** [comment]
Please can you provide the command you ran and and the output?

**Comment by Incedis** [comment]
1 - create new key for desired region - Ok
2 - ./autovpn -C -r ap-southeast-1 -k ap-southeast-1_vpnkey
And then I get the error code 5. AWS is refusing the key
Creating ec2 instance in ap-southeast-1. This can take some time...
Instance has been created 54.169.150.190
Giving new instance some time to fully boot up...
54.169.150.190 is still booting...                                                                                      
Setting up VPN on 54.169.150.190
Warning: Permanently added '54.169.150.190' (ECDSA) to the list of known hosts.
Permission denied (publickey).
lost connection
Error code 5

**Comment by ttlequals0** [comment]
What OS are you using? Did you aadd key to your ssh-agent?

**Comment by Incedis** [comment]
OS = linux 
key ssh agent = yes
my guess is the error is probably linked to amazon.key is being denied by aws usually for two reasons. One account used. Second key has bad permissions.

**Comment by ttlequals0** [comment]
What distributor of Linux?  Is hat is the full python traceback?

**Comment by Incedis** [comment]
Issue resolved - Recreated my keys. If you have a special character in the secret key, it may cause issue. 
I have initiated a setup with the  -p flag on port 443 with success. I now have issue with the connection which I did not have before. It simply won't connect.
