### ISSUE TITLE
Error VPCResourceNotSpecified

### ISSUE THREAD

**Issue by b0x42** [ttlequals0/autovpn#3]
Hi there,

when i am running `./autovpn -C -r us-east-1 -k macbook` I am getting the following error:

```
Creating ec2 instance in us-east-1. This can take some time...
Traceback (most recent call last):
  File "create_ec2.py", line 66, in <module>
    auto_vpn()
  File "create_ec2.py", line 51, in auto_vpn
    user_data=user_data)
  File "/usr/local/lib/python2.7/site-packages/boto/ec2/connection.py", line 977, in run_instances
    verb='POST')
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCResourceNotSpecified</Code><Message>The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.</Message></Error></Errors><RequestID>b864dabb-12b9-421a-8485-b675359b71dd</RequestID></Response>
Error code 4
```

Help is much appreciated
Thank you!
Ben

**Comment by ttlequals0** [comment]
So far i am unable to reproduce this issue. I will continue to look into this. Dose the api key you are using have permission to create or modify VPCs?

**Comment by ttlequals0** [comment]
This does not appear to be an issue with the script but rather AWS permission issues.

**Comment by ghost** [comment]
So what kind of permissions does this need? I gave it AmazonEC2FullAccess, IAMFullAccess and  AmazonVPCFullAccess and I still get the same error.

**Comment by ttlequals0** [comment]
What command did you use to launch instance.

**Comment by ghost** [comment]
./autovpn -C -r us-east-1 -k us-east-1_vpnkey

**Comment by ttlequals0** [comment]
On the aws management  console do you see a new VPC created?

**Comment by ghost** [comment]
Yes, I can see a new VPC created.

**Comment by macecchi** [comment]
I'm having the same issue as well. I don't see any VPC created though.
I'm using an account with full admin access, so it's not an issue with permissions.

**Comment by macecchi** [comment]
Apparently, this happens because I do not have a default VPC set in my account, and therefore it needs to be specified when creating an EC2 instance.

In that case I needed to use the `--subnet-id` and `--security-group-ids` args in `run-instances`. Also, the security group had to be recreated to belong to my VPC.

**Comment by magicalbanana** [comment]
@macecchi how did you exactly fix yours? I'm having the same issue because I deleted my default VPC and I am not really a pythoner.
