### ISSUE TITLE
custom port 443 with -p flag  and issue connecting to vpn 

### ISSUE THREAD

**Issue by Incedis** [ttlequals0/autovpn#30]
Set the -p flag on port 443 and created two vpn in two different regions successfully. 
In both region I had issue connection to the VPN. The connection was not successful probably due to some DNS issue; time out on the connection which is very symptomatic of bad DNS. The connection to the VPN was always successful. I do not have that issue with standard port. 
Anyone else had the issue ?

**Comment by ttlequals0** [comment]
Are you using the latest scripts? Please run a git pull. You might be describing the mssfix issue

**Comment by Incedis** [comment]
git pull got diff and the issue is fixed. thanks. 
fresh creating of vpn on port 443 and now it works as expected.
