### ISSUE TITLE
Error code 5

### ISSUE THREAD

**Issue by mcgilbert** [ttlequals0/autovpn#32]
Gets this far:

Giving new instance some time to fully boot up...
xx.xx.xx.xx is still booting...
Setting up VPN on xx.xx.xx.xx
Warning: Permanently added 'xx.xx.xx.xx' (ECDSA) to the list of known hosts.
Permission denied (publickey).
lost connection
Error code 5

Not sure what the debug procedure would be here. Likely PEBCAK, but I'm stuck.

**Comment by ttlequals0** [comment]
Looks like you need to add new key to your ssh-agent

**Comment by mcgilbert** [comment]
Pardon in advance my appalling ignorance, but the key that I used (using the -k command) is one that I have used before. Should I start from scratch with new keys?

**Comment by ttlequals0** [comment]
Is that key registered​ in your ssh-agent? Dose that key exist in the aws
region you are trying to use.

**Comment by mcgilbert** [comment]
Thank you for your patience. I was hasty when I checked earlier and there was a similarly named key in the agent registry, but not that one. autovpn has already prodded past that point and is working properly. Thank you SO MUCH for your patience.

P.S. Are the autovpn error codes definitions available?

**Comment by ttlequals0** [comment]
Glad to hear that you got it working.

As of now there really is no error code definitions. I should probably
create one, right now they act as markers in the code where something went
wrong.
