### ISSUE TITLE
Documentation should indicate '[default]' header for AWS credentials, not '[Credentials']

### ISSUE THREAD

**Issue by dakotareier** [ttlequals0/autovpn#33]
I tried to follow the step-by-step but couldn't generate a keypair because something was broken in the authentication step. 

Googling revealed that most ~/.aws/credentials files have a header of `[default]`, and when I changed my credentials file to use that section header the -G flag worked. 

I recommend updating docs in Dependencies, step 3 to reflect this.

(on MacOS Sierra latest)

**Comment by ttlequals0** [comment]
Thank you, I will update it.

**Comment by ttlequals0** [comment]
fixed with 8b5172d5f215255fb7f219b660b3c8c1a37755c5
