### ISSUE TITLE
no internet

### ISSUE THREAD

**Issue by neumachen** [ttlequals0/autovpn#35]
The VPN script works really well, however, just curious as to why when I create a new node without a public IP address, I am able to SSH into the machine but the machine can't connect to the internet. Any thoughts?

**Comment by ttlequals0** [comment]
Can you please elaborate on what you mean by "no internet" ?

**Comment by neumachen** [comment]
It means the node is unable to access the internet, the VPN node is fine, but the nodes within the same subnet as the VPN node can't access the internet.

**Comment by ttlequals0** [comment]
How many nodes are you connecting to the VPN endpoint in AWS.

**Comment by neumachen** [comment]
I don't think it's connected at all. I mean, once I am connected to the VPN I can ssh into the node, but when I run any commands that require the internet, well, nothing. I do realize this might be an AWS issue, but if you have some thoughts as to why it's doing so, I would greatly appreciate it.

**Comment by ttlequals0** [comment]
What OpenVPN client are you using? Dose the client show connected? Dose the virtual interface the OpenVPN client use have a valid IP when connected?
