### ISSUE TITLE
UnauthorizedOperation when running autovpn

### ISSUE THREAD

**Issue by dtsmith2001** [ttlequals0/autovpn#39]
Running

`./autovpn -G -r us-east-1`

I get the following error

```
Generating new keypair for us-east-1.
Traceback (most recent call last):
  File "./scripts/keygen.py", line 36, in <module>
    generate_key()
  File "./scripts/keygen.py", line 20, in generate_key
    key = ec2.get_all_key_pairs(keynames=[key_name])[0]
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2836, in get_all_key_pairs
    [('item', KeyPair)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>1774ef84-4d05-4f66-8774-737b5db4202b</RequestID></Response>
Key already exists in AWS
```

Ok, the key already exists. However, the next step

`./autovpn -C -r us-east-1 -k us-east-1_vpnkey`

also results in an error

```Creating ec2 instance in us-east-1. This can take some time...
Traceback (most recent call last):
  File "./scripts/create_ec2.py", line 69, in <module>
    auto_vpn()
  File "./scripts/create_ec2.py", line 30, in auto_vpn
    group = ec2.get_all_security_groups(groupnames=[group_name])[0]
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2984, in get_all_security_groups
    [('item', SecurityGroup)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>5fcb205d-a147-45ea-91f1-05c5a7515af4</RequestID></Response>
Error code 4
```

Any idea what operation is not authorized and how I give myself permissions? I checked the username in IAM associated with my secret key and it has AdministratorAccess permissions. I also verified my ```aws_access_key_id```.

```autovpn -S -r us-east-1```

reports

```No instances running in us-east-1```

I deleted the keypair using

```autovpn -C -r us-east-1 -D us-east-1_vpnkey```

but I still get an ```EC2ResponseError: 403 Forbidden``` message.

I also used the IAM Policy Simulator to check the create/delete key policy, and it reports _allowed_.

**Comment by dtsmith2001** [comment]
And I verified my key exists for ```us-east-1```.

**Comment by dtsmith2001** [comment]
After reading a few issues, and more on AWS key pairs, I imported a key pair and verified it's present in AWS EC2. I then tried

```autovpn -C -r us-east-1 -k my_key_name -u my_user_name```

using the username I created for myself (yes, I can log into AWS with it) and key name from ~/.ssh (without .pub). Yes, this is the keyname I imported to EC2. I am still getting the same error.

I suspect strongly that this is an EC2 problem when trying to create an instance. If anyone else had this problem and solved it, please let me know.

**Comment by dtsmith2001** [comment]
A last update for now. I added the permissions ```AmazonEC2FullAccess``` and ```AmazonEC2SpotFleetRole``` to my user permissions, and also to the group permissions as well. I still have the same problem.

**Comment by ttlequals0** [comment]
The -u is only needed if you chose an ami that has a default user other than ubuntu. The only thing you need to simply deploy an endpoint is to run.
`autovpn -C -r us-east-1 -k my_key_name`

It also looks like in earlier posts you were having permissions issues.
NOTE: make sure your ssh key is added to your users ssh-agent

**Comment by dtsmith2001** [comment]
I will check out the ssh-agent issue. Thanks.

**Comment by dtsmith2001** [comment]
Yes, adding my key to ssh-agent worked. Thanks.
