### ISSUE TITLE
autovpn -T -r us-east-1 does not shut down the instance

### ISSUE THREAD

**Issue by dtsmith2001** [ttlequals0/autovpn#40]
After starting an instance, running ```openvpn```, and terminating it, the command ```autovpn -T -r us-east-1``` does not stop the instance.

I also tried ```autovpn -T -r us-east-1 -i instance_id```. The instance_id can be obtained from the EC2 console or via ```aws ec2 describe-instances```.

**Comment by ttlequals0** [comment]
-z is to specify instance to terminate

**Comment by dtsmith2001** [comment]
Thanks, did something dumb.
