### ISSUE TITLE
Chrome reports DNS_PROBE_FINISHED_BAD_CONFIG when openvpn is run

### ISSUE THREAD

**Issue by dtsmith2001** [ttlequals0/autovpn#42]
I successfully started an instance with ```autovpn -C -r us-east-1 -k private_key 2>&1 | tee autovpn.txt```. I then ran ```sudo openvpn2 us-east-1_aws_vpn.ovpn 2>&1 | tee openvpn.txt```. Chrome reports an error.

I have attached both logs.

[autovpn.txt](https://github.com/ttlequals0/autovpn/files/1099971/autovpn.txt)
[openvpn.txt](https://github.com/ttlequals0/autovpn/files/1099972/openvpn.txt)

Let me know if you need anything else, or if I've done something stupid. And here is the .ovpn file.

[us-east-1_aws_vpn.txt](https://github.com/ttlequals0/autovpn/files/1099973/us-east-1_aws_vpn.txt)

**Comment by ttlequals0** [comment]
What are your DNS settings?

**Comment by dtsmith2001** [comment]
On OS X El Capitan version 10.11.6, I used

```scutil --dns | tee dns_info.txt```

and attached the file. I also read the man page for scutil

`The --dns option reports the current DNS configuration.  The first listed resolver(5) configuration is
     considered to be the "default" configuration.  Additional "supplemental" configurations follow.  Those
     containing a "domain" name will be used for queries matching the specified domain.  Those without will
     be used as a "default" configuration in addition to the first listed.`

Note that only my [Luma](https://lumahome.com/) is reachable and none of the others can be reached.

[dns_info.txt](https://github.com/ttlequals0/autovpn/files/1100500/dns_info.txt)

**Comment by ttlequals0** [comment]
Was that from when you were connected?  If so it looks like you openvpn client isn't using the DNS settings in the openvpn config.

**Comment by dtsmith2001** [comment]
I am using ```openvpn2``` from Macports. Let me take a look at the documentation and get back to you.

I have my laptop here at work so I can check this in a couple of hours.

**Comment by dtsmith2001** [comment]
The problem is OpenVPN does not play nice with the OS X networking. I'm still looking into possible solutions and will report back

**Comment by dtsmith2001** [comment]
And after doing more reading, I see that [TunnelBlick](https://tunnelblick.net/) is the preferred choice on OS X. As this is a client issue, I'll close this issue.
