### ISSUE TITLE
Bidirectional network access (ec2 <-> on-premises)

### ISSUE THREAD

**Issue by ghost** [ttlequals0/autovpn#44]
Hi,

Just wonder what I should do for enabling dual ways connections? Have done:

1. [AWS] Disable source / destination check on EC2 instance <script launched instance> > Actions > Networking > Change Source/Destination check
2. [AWS] VPC > Route Tables > <select the route table binding to which subnet> > Routes > Edit > <given  on-premise subnet CIDR block for Destination, and select the script launched instance as Target> > Save.
3. [On-premise] Router (home router) does similar things on LAN, but change destination subnet to AWS VPC CIDR block (e.g. 172.31.0.0/16)

Current result:
- On-premise could ping instances on AWS VPC instances, but AWS VPC instances can't ping those VMs on on-premise. 

For example, my on-premise VM IP address is 10.10.11.5, and AWS VPC instance private ip (not script launched instance) is 172.31.19.33, 172.31.21.175, etc. 10.10.11.5 -> 172.31.19.33 / 172.31.21.175 OK, but 172.31.19.33 / 172.31.21.175 -> 10.10.11.5 failed.

**Comment by ttlequals0** [comment]
You can reach your systems on-premises, however you will need to use the tunnel network.

Notice if you run `ip a` on the ec2 instance there is a tun0 interface.
`3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none
    inet 10.8.0.1/24 brd 10.8.0.255 scope global tun0
       valid_lft forever preferred_lft forever`

The on-premises system will also be on this same network. typically at ip of ` 10.8.0.2` you should be able to ping and even ssh into this device.

if you want to access all devices on your local network you will need to essentially turn the system you ran the script on to be a router by adding static routes and enabling ` net.ipv4.ip_forward = 1`

**Comment by ghost** [comment]
Thanks for advice. I will give a try. Close for now.
