### ISSUE TITLE
vpn to ec2 instances in a different peered vpc on the same region on the same aws account

### ISSUE THREAD

**Issue by alleles** [ttlequals0/autovpn#50]
first thanks for this tool.. I've used it countless times.. it works like a charm.. I have a customer who has a default vpc which contains the ec2 instance that runs this vpn.. and it also has a peered vpc which i can connect to if i ssh to the vpn ec2 instance.. however if i just connect to the vpn I can't ssh to the instances in the vpc that is peered to the one that the vpn ec2 is in.. sorry for being a noob.. <3

**Comment by ttlequals0** [comment]
This sounds like a routing issue between the VPN endpoint and and instance in peered VPC. you will need to SSH to VPN ec2 instance and add some static routes that point to instance in peered VPC. You also might need to disable source destination check on the ec2 instance see https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck.

**Comment by alleles** [comment]
wow thanks! that did it.. You're the best!

https://www.youtube.com/watch?v=E-WHW-QNswE
