### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by jhagege** [ttlequals0/autovpn#9]
Hi,

Great script, helps tons !
We tried to use the same config file that was generated on multiple clients but each time it disconnects the other one.

It seems only one user would be allowed at the same time.
Do you know of a way to generate multiple client keys for the OpenVPN Server (one per client) ?
Can you think of a better way ? Maybe username/password for each client ? 

Thanks

**Comment by ttlequals0** [comment]
Thanks for the feedback. 

Ideally you wouldn't want to use the same config file for each client however it is possible. 

I will try to find a way to either allow same config file or integrate a way to add more users. 

Taking a closer look it should be easy fro me to create an option that will allow multiple clients to use the same certs.

**Comment by ttlequals0** [comment]
I have added an option to allow for multi-user support. let me know if this solves your problem.
https://github.com/ttlequals0/autovpn/tree/feature/multi-user

usage:
./autovpn -C -r \<region\> -k \<key\> -m

**Comment by jhagege** [comment]
Excellent, it seems to work fine, thanks ! 
If I would want to generate more certificates for multiple users, would it be easy to do so ? Even manually.
Do you know of a way ? 
Thanks

**Comment by ttlequals0** [comment]
login to ec2 instance ubuntu@\<ip_address\>
wget git.io/v35Kx --no-check-certificate -O openvpn-install.sh; sudo bash openvpn-install.sh
Option 1 - hit enter
give name for client - hit enter
from your machine 
scp ubuntu@\<ip_address\>:~/\<client_name\>.ovpn ./

**Comment by jhagege** [comment]
Thanks tons ! 
It helped a lot :-)
